= Welcome to the team! 

Hi! Welcome to your first day on the team.  

We run a number of Red Hat Enterprise Linux systems, and all of them have problems, in this lab, and the ones that follow it, you will be asked to solve some common issues that you may encounter as a Red Hat Enterprise Linux system administrator.  Don't worry though, you're not on your own.  The lab will guide you through the core principles that you need in order to find and solve these issues. 

== The Lab Environment 

On your right, you should see a terminal, where you are connected to a Red Hat Enterprise Linux 10 system.  

All of the work you will be doing in this lab will be inside of that terminal.  Thruout the lab, we may add additional terminals or web browser tabs at the top of the terminal window. 

This instructions pane that you are reading, will guide you through the lab.  We will tell you if you need to switch to a different tab.  

The instructions will also include blocks of commands that you are meant to run in the terminal.  These are called Command Blocks, and will have a copy to clipboard button at the top.  Pressing that button will copy the entire block to your clipboard, and then you can paste it into the terminal by right-clicking, and selecting Paste. An example of a Command Block follows:

[source,bash,role="execute",subs=attributes+]
----
ls -l /etc
----

You will also see Output Blocks, which are meant to show you what the output of a command should look like.  Please keep in mind that sometimes the Command Output blocks may not exactly match the output on your screen, but they should give you a general idea of what the output should look like to compare to what your system is reporting. Those look like this:

[source,subs=attributes+]
----
[rhel@rhel ~]$ ls -l /etc
total 1232
-rw-r--r--.  1 root root   5923 Nov 26  2024 DIR_COLORS
-rw-r--r--.  1 root root   6005 Nov 26  2024 DIR_COLORS.lightbgcolor
-rw-r--r--.  1 root root     94 Oct 29  2024 GREP_COLORS
drwxr-xr-x.  7 root root    134 May 15  2025 NetworkManager
drwxr-xr-x.  2 root root     48 Jun 17  2025 PackageKit
drwxr-xr-x.  5 root root     51 Jun 17  2025 X11
drwxr-xr-x.  4 root root     35 Jun 17  2025 acpi
-rw-r--r--.  1 root root     12 Feb 13  2025 adjtime
-rw-r--r--.  1 root root   1529 Nov 29  2023 aliases
drwxr-xr-x.  2 root root   4096 Jun 17  2025 alternatives
-rw-r--r--.  1 root root    541 Dec 11  2024 anacrontab
...
----


Now let's head on to the next step, and get started! 

