= Welcome to the team! 

Hi! Welcome to your first day on the team.  

We run a number of Red Hat Enterprise Linux systems, and all of them have problems, in this lab, and the ones that follow it, you will be asked to solve some common issues that you may encounter as a Red Hat Enterprise Linux system administrator.  Don't worry though, you're not on your own.  The lab will guide you through the core principles that you need in order to find and solve these issues. 

== The Lab Environment 

On your right, you should see a terminal, where you are connected to a Red Hat Enterprise Linux 10 system.  

All of the work you will be doing in this lab will be inside of that terminal.  Thruout the lab, we may add additional terminals or web browser tabs at the top of the terminal window. 

This instructions pane that you are reading, will guide you through the lab.  We will tell you if you need to switch to a different tab.  

The instructions will also include blocks of commands that you are meant to run in the terminal.  These are called Command Blocks, and will have a copy to clipboard button at the top.  Pressing that button will copy the entire block to your clipboard, and then you can paste it into the terminal by right-clicking, and selecting Paste. An example of a Command Block follows:

[source,bash,role="execute",subs=attributes+]
----
ls -l /etc
----

You will also see Output Blocks, which are meant to show you what the output of a command should look like.  Please keep in mind that sometimes the Command Output blocks may not exactly match the output on your screen, but they should give you a general idea of what the output should look like to compare to what your system is reporting. Those look like this:

[source,subs=attributes+]
----
some ls /etc output here.
----


Now let's head on to the next step, and get started! 

